planned to work on the unique method but ended up changing the delete…
berlindiamonds/discourse-sync-to-dropbox pull request #21
Opened 2017-08-09 15:08 UTC by kajatiger

… old files method because the path for the delete argument was wrong

2017-08-09 16:18 UTC, jen-v commented
hey Kaja can you please leave some more descriptive message when you send a PR? 
I don't understand what or why you mean with "the path for the delete argument was wrong". 
Thanks!

2017-08-09 17:10 UTC, jenni requested changes
I cannot reproduce the issue. I've tried with a nonexistent folder, it's created and keeps always 5 backups in it. I've tried with 2 new folders, and several backups.

How did you get this error to happen?

```
trash.each {|f| @dbx.delete("/#{folder_name}/#{f}")}
Dropbox::ApiError: path_lookup/not_found/.
from /Users/kaja/code/discourse/plugins/discourse-sync-to-dropbox/gems/2.4.1/gems/dropbox-sdk-v2-0.0.3/lib/dropbox/client.rb:349:in `request'
```
Why do you want to use f.path_lower?

f.path_lower is the same as: 
"/#{folder_name}/#{f}" 

both translate into:
"/folder/filename.jpg"

I did get this error using delete on an empty array with f.path_lower :

```
[17] pry(main)> x = trash.each {|f| dbx.delete("#{f.path_lower}")}
Dropbox::ApiError: path_lookup/not_found/
from /Users/jlijo/Documents/discourse/plugins/discourse-sync-to-dropbox/gems/2.4.0/gems/dropbox-sdk-v2-0.0.3/lib/dropbox/client.rb:349:in `request'
```

2017-08-10 07:29 UTC, kajatiger commented
I got this error because the array in trash was an array of files and not of filenames. So f wasn't the name for the path anymore. path_lower is safer and shorter, if it works for you, we should keep it

2017-08-10 08:02 UTC, jenni approved these changes

2017-08-10 08:02 UTC, merged